#!/bin/bash

trap "echo 'ERROR running/starting haproxy'; exit -1" ERR


# log to external
LOGDIR=/logs
LOG=$LOGDIR/haproxy.log

touch $LOG

echo -n "START: " >> $LOG
date >> $LOG

rsyslogd

if [ ! -e /conf/server-cert.pem ]; then
    echo "ERROR: Missing /conf/server-cert.pem. Mount /conf to the location of the cert file on local host." && exit -1 >> $LOG 
fi

update-ca-trust
haproxy "$@"

echo -n "init DONE: " >> $LOG
date >> $LOG
