#!/bin/bash

trap "echo 'ERROR running/starting haproxy'; exit -1" ERR


CONFDIR=/config
LOG=/logs/haproxy.log

echo -n "START: " > $LOG
date >> $LOG

if [ ! -e $CONFDIR ]; then
    echo "ERROR: Missing $CONFIDR mount directory. It is required for configuration." >> $LOG
    exit -1
fi

if [ ! -e $CONFDIR/server-cert.pem ]; then
    echo "ERROR: Missing $CONFDIR/server-cert.pem."  >> $LOG 
    exit -1
fi

if [ -e $CONFDIR/cacerts ]; then
    echo "Configure CA bundle with extra certificates from $CONFDIR/cacerts" >> $LOG
    cp $CONFDIR/cacerts/* /etc/pki/ca-trust/source/anchors/
    update-ca-trust
else
    echo "No extra certificates to configure the CA bundle found" >> $LOG
fi

if [ -e $CONFDIR/haproxy.cfg ]; then
    cp $CONFDIR/haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg
    echo "Using custom haproxy.cfg found in $CONFDIR" >> $LOG
fi
       
echo -n "init DONE: " >> $LOG
date >> $LOG

# run on foreground
/usr/sbin/haproxy -f /usr/local/etc/haproxy/haproxy.cfg  >> $LOG

