FROM centos:7 

# external URLs; allow --build-arg switch
ARG PGDG=https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
ARG PGSPHERE=https://www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/software/pgsphere12-1.2.0-1.el7.x86_64.rpm

# repositories and keys
RUN yum -y install centos-release-scl epel-release ${PGDG} \
    && rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7 \
    && rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-SCLo \
    && rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-PGDG \
    && rpm -q gpg-pubkey --qf '%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n'
    
# packages
RUN yum -y install postgresql12-server postgresql12-contrib ${PGSPHERE} \
    && yum -y clean all

RUN mkdir -p /logs
COPY src/init/* /var/lib/pgsql/12/

COPY src/cadc-dev-postgresql-start-12 /usr/bin/cadc-dev-postgresql-start
CMD ["/usr/bin/cadc-dev-postgresql-start"]

