FROM centos:7 

# To allow the --build-arg switch
ARG PG_RPM_URL=https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm

# install required software
RUN yum update -y

# repositories and keys
RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm \
    && rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
RUN yum install -y ${PG_RPM_URL} \
    && rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-PGDG

# packages
RUN  yum -y install postgresql12-server-12.3-1PGDG.rhel7 postgresql12-contrib-12.3-1PGDG.rhel7

# TODO: add CADC build of pgsphere for postgresql12-server
#RUN yum -y install https://www.cadc-ccda.hia-iha.nrc-cnrc.gc.ca/software/pgsphere10-1.1.5-1.el7.centos.x86_64.rpm

RUN yum clean all

RUN mkdir -p /logs
COPY src/init/* /var/lib/pgsql/12/

COPY src/cadc-dev-postgresql-start-12 /usr/bin/cadc-dev-postgresql-start
CMD ["/usr/bin/cadc-dev-postgresql-start"]

