#!/bin/bash

SELF=cadc-tomcat-start

CONFDIR=/config
USER=$(whoami)

TS=$(date)
echo "$TS $SELF START"
echo "user: $USER"
echo "home: $HOME"

if [ -f $CONFDIR/catalina.properties ]; then
    echo "Configure tomcat with extra properties: $CONFDIR/catalina.properties"
    cat $CONFDIR/catalina.properties >> /etc/tomcat/catalina.properties
fi

if [ -f $CONFDIR/war-rename.conf ]; then
    while read line
    do
        MV=$(echo $line | awk '{print $1}')
        if [ "$MV" != "mv" ]; then
            echo "war-rename: $line SKIPPED"
        else
            echo "war-rename: $line"
            cd /usr/share/tomcat/webapps && $line
        fi
    done < $CONFDIR/war-rename.conf
fi

if [ -f $CONFDIR/tomcat.conf ]; then
    echo "Configure tomcat with extra properties: $CONFDIR/tomcat.conf"
    cat $CONFDIR/tomcat.conf >> /etc/tomcat/tomcat.conf
fi

if [ -e $CONFDIR/cacerts ]; then
    echo "Configure CA bundle with extra certificates: $CONFDIR/cacerts"
    cp $CONFDIR/cacerts/* /etc/pki/ca-trust/source/anchors/
    sudo update-ca-trust
fi

if [ -e $CONFDIR/lib ]; then
    echo "Add extra jars to tomcat classpath: $CONFDIR/lib"
    cp $CONFDIR/lib/* /usr/share/tomcat/lib/
fi

for pcf in $CONFDIR/*.pem; do
    echo "Link proxy certificate: $pcf"
    mkdir $HOME/.ssl
    chmod 700 $HOME/.ssl
    ln -s $pcf $HOME/.ssl/
done

## brutal CADC-spcific hack
if [ -e $CONFDIR/dbrc ]; then
    echo "Link dbrc file: $CONFDIR/dbrc"
    ln -s $CONFDIR/dbrc /usr/share/tomcat/.dbrc
fi

ln -s /config $HOME/config

TS=$(date)
echo "$TS $SELF DONE"

/usr/libexec/tomcat/server start

