#!/bin/bash

export PGBASE=/var/lib/pgsql
export VER=17

# log to external
LOGDIR=/logs
LOG=$LOGDIR/do-init.log

touch $LOG

echo -n "START: " >> $LOG
date >> $LOG 

INITDB=0

if [ -e $PGBASE/$VER/data/postgresql.conf ]; then
    echo "do-init: detected existing setup... skipping database init" >> $LOG
else
    INITDB=1
fi

if [ $INITDB == 1 ]; then
    echo "initialising server..." >> $LOG
    /usr/local/bin/pgdb-init-postgres.sh >> $LOG
fi

echo "start postgresql server..." >> $LOG
/usr/pgsql-${VER}/bin/postgres -D $PGBASE/$VER/data >& $LOGDIR/postgresql.log &
PGPID=$!
echo "start postgresql server... $PGPID" >> $LOG

echo "waiting for postgresql server to become ready..." >> $LOG
# TODO: loop and call pg_isready until ready?
sleep 6


if [ $INITDB == 1 ]; then
    echo "initialising content..." >> $LOG
    if [ -e /config/init-content-schemas.sh ]; then
        # create standard user(s), database(s), schema(s)
        /usr/local/bin/pgdb-init-content.sh >> $LOG
    else
        echo "not found: /config/init-content-schemas.sh" >> $LOG
    fi
fi

echo -n "init DONE: " >> $LOG
date >> $LOG

echo "waiting for postmaster to terminate..." >> $LOG
wait $PGPID
echo "wait returned... exiting" >> $LOG
