#!/bin/bash

# log to external
LOGDIR=/logs
LOG=$LOGDIR/do-init.log

touch $LOG

echo -n "START: " >> $LOG
date >> $LOG

INITDB=0

if [ -e /var/lib/pgsql/10/data/postgresql.conf ]; then
    echo "do-init: detected existing setup... skipping database init" >> $LOG
else
    INITDB=1
fi

if [ $INITDB == 1 ]; then
    # change ownership of injected config files
    chown -R postgres.postgres /var/lib/pgsql/10/*
    su -l postgres -c '/bin/bash /var/lib/pgsql/10/init-postgres.sh' >> $LOG
fi

# start postgresql server
su -l postgres -c '/usr/pgsql-10/bin/postmaster -D /var/lib/pgsql/10/data' > $LOGDIR/postgresql.log &

sleep 6
if [ $INITDB == 1 ]; then
    # create standard user(s), database(s), schema(s)
    su -l postgres -c '/bin/bash /var/lib/pgsql/10/init-content.sh' >> $LOG
fi

echo -n "init DONE: " >> $LOG
date >> $LOG

echo "waiting for postmaster to terminate..." >> $LOG
wait
echo "wait returned... exiting" >> $LOG
